#!/usr/bin/env python
"""
This script takes the role of what ``manage.py`` usually does in a django
project.  We have this script simply there in order to have a nicer name for it.
``./otree runserver`` is just a lot cooler than ``python manage.py runserver``.

However this has one drawback. There are commands (namely celery) that won't
work if the command is not run from ``manage.py``. Also other tools like PyCharm
sometimes expect to have a ``manage.py`` around. So we keep the ``manage.py``
next to this ``./otree`` script to support more tools.
"""

import os
import sys


if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")

    from otree.management.cli import execute_from_command_line
    execute_from_command_line(sys.argv, script_file=__file__)
