#!/usr/bin/env python
"""
This script shall help in deploying otree to a heroku instance.
Type './otree-heroku help' to get a list of all available commands.
"""

import os
import sys


if __name__ == "__main__":
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'settings')

    from otree.management.deploy.heroku import execute_from_command_line
    execute_from_command_line(sys.argv)
